[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "always"

# Web service configuration
[[services]]
name = "web"
healthcheckPath = "/"
healthcheckTimeout = 300

# Worker service configuration
[[services]]  
name = "worker"

[environments.production]
variables = { RAILWAY_ENVIRONMENT = "production" }