[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "always"

# Only web services need health checks
[[services]]
name = "web"
healthcheckPath = "/"
healthcheckTimeout = 300

# Worker services don't need health checks
[[services]]  
name = "worker"
# No healthcheck configuration

[environments.production]
variables = { RAILWAY_ENVIRONMENT = "production" }
