# Generated by Django 4.2.7 on 2025-07-22 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='The question/front side of the flashcard')),
                ('answer', models.TextField(help_text='The answer/back side of the flashcard')),
                ('source_file', models.CharField(help_text='Name of the markdown file this was generated from', max_length=255)),
                ('source_content', models.TextField(blank=True, help_text='Original markdown content section')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(help_text='Path to the folder containing markdown files', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_files', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_page', models.IntegerField(default=1)),
                ('cards_per_page', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('cards_shown', models.ManyToManyField(blank=True, related_name='shown_in_sessions', to='flashcards.flashcard')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='flashcards.folder')),
            ],
            options={
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.folder'),
        ),
    ]
