# Generated by Django 4.2.7 on 2025-07-23 17:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('extracted_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={},
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='source_content',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='tags',
            field=models.JSONField(default=list, help_text='List of relevant tags'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.folder'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='source_file',
            field=models.CharField(blank=True, help_text='Original source file name', max_length=255),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='cards_shown',
            field=models.ManyToManyField(blank=True, to='flashcards.flashcard'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='flashcards.folder'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.pdfdocument'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='flashcards.pdfdocument'),
        ),
    ]
