# Generated by Django 4.2.7 on 2025-07-26 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_pdfdocument_alter_studysession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='cleaned_text',
            field=models.TextField(blank=True, help_text='Processed and cleaned text'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Word count of cleaned text'),
        ),
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_text', models.TextField(help_text='The actual chunk content')),
                ('chunk_order', models.IntegerField(help_text='Order of this chunk in the document')),
                ('word_start', models.IntegerField(help_text='Starting word position in original text')),
                ('word_end', models.IntegerField(help_text='Ending word position in original text')),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_chunks', to='flashcards.pdfdocument')),
            ],
            options={
                'ordering': ['pdf_document', 'chunk_order'],
                'unique_together': {('pdf_document', 'chunk_order')},
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='text_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.textchunk'),
        ),
    ]
