# Generated by Django 4.2.7 on 2025-07-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_pdfdocument_concepts_analyzed_conceptunit_chunklabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptunit',
            name='cognitive_load',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', help_text='Cognitive load required', max_length=20),
        ),
        migrations.AddField(
            model_name='conceptunit',
            name='complexity_score',
            field=models.FloatField(default=0.5, help_text='Content complexity score (0-1)'),
        ),
        migrations.AddField(
            model_name='conceptunit',
            name='estimated_reading_time',
            field=models.FloatField(default=0.0, help_text='Estimated reading time in minutes (LLM calculated)'),
        ),
        migrations.AddField(
            model_name='conceptunit',
            name='original_order',
            field=models.IntegerField(blank=True, help_text='Original order before optimization', null=True),
        ),
        migrations.AddField(
            model_name='conceptunit',
            name='time_optimized',
            field=models.BooleanField(default=False, help_text='Whether this unit has been time-optimized'),
        ),
    ]
