# Generated by Django 4.2.7 on 2025-07-26 07:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_conceptunit_cognitive_load_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_order', models.IntegerField(help_text='Order of this focus block in the study sequence')),
                ('title', models.CharField(help_text='Auto-generated focus block title', max_length=255)),
                ('target_duration', models.FloatField(default=6.5, help_text='Target duration in minutes (6-7 min)')),
                ('teacher_script', models.TextField(help_text='LLM-generated psychology-aware teaching script')),
                ('rescue_reset', models.TextField(help_text='Content to help students who get lost')),
                ('recap_summary', models.TextField(help_text='Final recap and key takeaways')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('learning_objectives', models.JSONField(default=list, help_text='List of learning objectives for this block')),
                ('prerequisite_concepts', models.JSONField(default=list, help_text='Concepts that should be understood first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_concept_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_focus_blocks', to='flashcards.conceptunit')),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_blocks', to='flashcards.pdfdocument')),
                ('revision_concept_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_focus_blocks', to='flashcards.conceptunit')),
            ],
            options={
                'ordering': ['pdf_document', 'block_order'],
                'unique_together': {('pdf_document', 'block_order')},
            },
        ),
        migrations.AddField(
            model_name='studysession',
            name='session_type',
            field=models.CharField(choices=[('flashcards', 'Flashcards'), ('focus_blocks', 'Focus Blocks'), ('mixed', 'Mixed')], default='focus_blocks', max_length=20),
        ),
        migrations.AddField(
            model_name='studysession',
            name='completed_focus_blocks',
            field=models.ManyToManyField(blank=True, related_name='completed_sessions', to='flashcards.focusblock'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='current_focus_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sessions', to='flashcards.focusblock'),
        ),
        migrations.CreateModel(
            name='QAItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='The question to ask')),
                ('answer', models.TextField(help_text='The expected answer')),
                ('item_order', models.IntegerField(help_text='Order within the focus block (1 or 2)')),
                ('question_type', models.CharField(choices=[('comprehension', 'Comprehension'), ('application', 'Application'), ('analysis', 'Analysis'), ('synthesis', 'Synthesis'), ('evaluation', 'Evaluation'), ('recall', 'Recall')], default='comprehension', max_length=50)),
                ('cognitive_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=20)),
                ('hints', models.JSONField(default=list, help_text='Progressive hints if student struggles')),
                ('explanation', models.TextField(blank=True, help_text='Detailed explanation of the answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('focus_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_items', to='flashcards.focusblock')),
            ],
            options={
                'ordering': ['focus_block', 'item_order'],
                'unique_together': {('focus_block', 'item_order')},
            },
        ),
    ]
