# Generated by Django 4.2.7 on 2025-07-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_focusblock_studysession_session_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusblock',
            name='compact7_data',
            field=models.JSONField(default={}, help_text='Complete Compact7 template JSON structure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='focusblock',
            name='learning_objectives',
            field=models.JSONField(default=list, help_text='List of learning objectives'),
        ),
        migrations.AlterField(
            model_name='focusblock',
            name='prerequisite_concepts',
            field=models.JSONField(default=list, help_text='Prerequisite concepts'),
        ),
        migrations.AlterField(
            model_name='focusblock',
            name='recap_summary',
            field=models.TextField(blank=True, help_text='Legacy recap'),
        ),
        migrations.AlterField(
            model_name='focusblock',
            name='rescue_reset',
            field=models.TextField(blank=True, help_text='Legacy rescue content'),
        ),
        migrations.AlterField(
            model_name='focusblock',
            name='target_duration',
            field=models.FloatField(default=420, help_text='Target duration in seconds (7 min = 420 sec)'),
        ),
        migrations.AlterField(
            model_name='focusblock',
            name='teacher_script',
            field=models.TextField(blank=True, help_text='Legacy teaching script'),
        ),
        migrations.DeleteModel(
            name='QAItem',
        ),
    ]
