# Generated by Django 4.2.7 on 2025-07-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_focusblock_compact7_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='content_fingerprint',
            field=models.TextField(blank=True, help_text='Short text fingerprint for fuzzy matching'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='content_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of cleaned text', max_length=64),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Original PDF this is a duplicate of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='flashcards.pdfdocument'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Whether this is a duplicate of another PDF'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='similarity_score',
            field=models.FloatField(default=0.0, help_text='Similarity score with original (0-1)'),
        ),
    ]
