# Generated by Django 4.2.7 on 2025-07-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_pdfdocument_content_fingerprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
