# Generated by Django 4.2.7 on 2025-07-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_alter_pdfdocument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusblock',
            name='title',
            field=models.CharField(help_text='Focus block title', max_length=500),
        ),
    ]
