# Generated by Django 4.2.7 on 2025-07-27 06:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_alter_focusblock_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_segment', models.IntegerField(default=0, help_text='Current segment index')),
                ('segments_completed', models.JSONField(default=list, help_text='List of completed segment indices')),
                ('total_study_time', models.FloatField(blank=True, help_text='Actual time spent in seconds', null=True)),
                ('segment_times', models.JSONField(default=dict, help_text='Time spent on each segment')),
                ('proficiency_score', models.IntegerField(blank=True, choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], help_text='Self-assessed proficiency score (1-5)', null=True)),
                ('difficulty_rating', models.IntegerField(blank=True, choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], help_text='How difficult was this content? (1=easy, 5=hard)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('learning_notes', models.TextField(blank=True, help_text="Student's notes during session")),
                ('confusion_points', models.JSONField(default=list, help_text='Segments where student got confused')),
                ('focus_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='flashcards.focusblock')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
