# Generated by Django 4.2.7 on 2025-07-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_focussession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='concepts_analyzed',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='content_fingerprint',
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='cleaned_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='flashcards.pdfdocument'),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
