# Generated by Django 4.2.7 on 2025-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_remove_pdfdocument_concepts_analyzed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='processing_duration',
            field=models.FloatField(blank=True, help_text='Processing time in seconds', null=True),
        ),
    ]
