# Generated by Django 4.2.7 on 2025-08-01 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0013_pdfdocument_processing_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusBlockRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('prerequisite', 'Prerequisite'), ('builds_on', 'Builds On'), ('related', 'Related'), ('applies_to', 'Applies To'), ('compares_with', 'Compares With'), ('specializes', 'Specializes')], max_length=20)),
                ('confidence', models.FloatField(help_text='AI confidence in this relationship (0-1)')),
                ('similarity_score', models.FloatField(help_text='Semantic similarity score (0-1)')),
                ('edge_strength', models.FloatField(help_text='Combined relationship strength (0-1)')),
                ('description', models.TextField(help_text='AI-generated description of the relationship')),
                ('educational_reasoning', models.TextField(help_text='Why this relationship helps learning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='flashcards.focusblock')),
                ('to_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='flashcards.focusblock')),
            ],
            options={
                'ordering': ['-edge_strength', '-confidence'],
                'unique_together': {('from_block', 'to_block', 'relationship_type')},
            },
        ),
    ]
