# Generated by Django 4.2.7 on 2025-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_focusblockrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='current_segment',
            field=models.IntegerField(default=0, help_text='Current segment index in current block'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='segment_progress',
            field=models.JSONField(default=dict, help_text='Completed segments per block: {block_id: [0,1,2,...]}'),
        ),
    ]
