# Generated by Django 4.2.7 on 2025-08-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_studysession_current_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='advanced_chunks',
            field=models.JSONField(blank=True, default=dict, help_text='Community-detected chunks with embeddings and metadata'),
        ),
    ]
