# Generated by Django 4.2.7 on 2025-08-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0016_pdfdocument_advanced_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusblock',
            name='content_embedding',
            field=models.JSONField(blank=True, default=list, help_text='Semantic embedding vector for deduplication (1536 dimensions)'),
        ),
        migrations.AddField(
            model_name='focusblock',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash of content for quick duplicate detection', max_length=64),
        ),
        migrations.AddField(
            model_name='focusblock',
            name='is_merged',
            field=models.BooleanField(default=False, help_text='True if this block was created by merging duplicates'),
        ),
        migrations.AddField(
            model_name='focusblock',
            name='merged_from_blocks',
            field=models.JSONField(default=list, help_text='List of block IDs that were merged into this one'),
        ),
    ]
