# Generated by Django 5.2.4 on 2025-08-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0017_focusblock_content_embedding_focusblock_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='block_completion_data',
            field=models.JSONField(default=dict, help_text="Block completion data: {block_id: {rating: 1-5, time_spent: seconds, notes: 'text', timestamp: 'ISO'}}"),
        ),
    ]
