# Generated by Django 4.2.7 on 2025-08-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0018_studysession_block_completion_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='mix_ratio_review',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='studysession',
            name='plan_position',
            field=models.IntegerField(default=0, help_text='Index into planned_blocks for current position'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='planned_blocks',
            field=models.JSONField(default=list, help_text='Ordered list of planned FocusBlock ids as strings'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='studysession',
            name='target_duration_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
