# Generated by Django 4.2.7 on 2025-08-20 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0019_studysession_ended_at_studysession_mix_ratio_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlockState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('lapsed', 'Lapsed'), ('suspended', 'Suspended')], default='new', max_length=20)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0, help_text='Number of times reviewed')),
                ('lapses', models.IntegerField(default=0, help_text='Number of times marked as difficult/forgotten')),
                ('ease_factor', models.FloatField(default=2.5, help_text='SM-2 ease factor (1.3-4.0)')),
                ('stability', models.FloatField(default=1.0, help_text='Memory stability in days')),
                ('avg_rating', models.FloatField(blank=True, help_text='Average proficiency rating (1-5)', null=True)),
                ('recent_qa_score', models.FloatField(blank=True, help_text='Recent Q&A accuracy (0-1)', null=True)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total study time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='flashcards.focusblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_at', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='flashcards__user_id_93c176_idx'), models.Index(fields=['next_due_at'], name='flashcards__next_du_3f12e1_idx'), models.Index(fields=['status', 'next_due_at'], name='flashcards__status_b81ec5_idx')],
                'unique_together': {('user', 'block')},
            },
        ),
    ]
