# Generated by Django 5.2.4 on 2025-08-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0020_userblockstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='cleaned_text',
        ),
    ]
