# Generated by Django 5.2.4 on 2025-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0021_remove_cleaned_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='content_fingerprint',
            field=models.TextField(blank=True, help_text='Content fingerprint for fuzzy matching'),
        ),
    ]
