# Generated by Django 5.2.4 on 2025-08-25 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0022_add_content_fingerprint_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userblockstate',
            options={'ordering': ['next_due_after_blocks', 'next_due_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='userblockstate',
            name='blocks_interval',
            field=models.IntegerField(default=1, help_text='Current block interval for spaced repetition'),
        ),
        migrations.AddField(
            model_name='userblockstate',
            name='blocks_studied_count',
            field=models.IntegerField(default=0, help_text='Total blocks studied since last review of this block'),
        ),
        migrations.AddField(
            model_name='userblockstate',
            name='next_due_after_blocks',
            field=models.IntegerField(blank=True, help_text='Number of blocks that need to be studied before this is due for review', null=True),
        ),
        migrations.AddField(
            model_name='userblockstate',
            name='stability_blocks',
            field=models.FloatField(default=1.0, help_text='Memory stability measured in number of blocks'),
        ),
        migrations.AddIndex(
            model_name='userblockstate',
            index=models.Index(fields=['next_due_after_blocks'], name='flashcards__next_du_d9264d_idx'),
        ),
        migrations.AddIndex(
            model_name='userblockstate',
            index=models.Index(fields=['user', 'next_due_after_blocks'], name='flashcards__user_id_80564a_idx'),
        ),
        migrations.AddIndex(
            model_name='userblockstate',
            index=models.Index(fields=['status', 'next_due_after_blocks'], name='flashcards__status_97ffdf_idx'),
        ),
    ]
