# Generated by Django 5.2.4 on 2025-08-25 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0023_add_block_based_scheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.IntegerField(default=0, help_text='Current position in the dynamic sequence (0-based)')),
                ('total_blocks_studied', models.IntegerField(default=0, help_text='Total number of blocks studied by this user')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_study_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
